-- MySQL Script generated by MySQL Workbench
-- Fri 17 Nov 2017 05:22:09 PM +0330
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gordcms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gordcms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gordcms` DEFAULT CHARACTER SET latin1 ;
USE `gordcms` ;

-- -----------------------------------------------------
-- Table `gordcms`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gordcms`.`categories` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gordcms`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gordcms`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` TINYTEXT NULL DEFAULT NULL,
  `Image` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gordcms`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gordcms`.`posts` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(400) NOT NULL,
  `Submit` DATETIME NOT NULL,
  `Content` LONGBLOB NULL DEFAULT NULL,
  `Body` LONGTEXT NULL DEFAULT NULL,
  `CategoryId` INT(11) NOT NULL,
  `UserId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_posts_category_idx` (`CategoryId` ASC),
  INDEX `fk_posts_user_idx` (`UserId` ASC),
  CONSTRAINT `fk_posts_category`
    FOREIGN KEY (`CategoryId`)
    REFERENCES `gordcms`.`categories` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_user`
    FOREIGN KEY (`UserId`)
    REFERENCES `gordcms`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;

USE `gordcms` ;

-- -----------------------------------------------------
-- Placeholder table for view `gordcms`.`post_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gordcms`.`post_details` (`ID` INT, `Title` INT, `Submit` INT, `CategoryID` INT, `CategoryName` INT, `UserID` INT, `Username` INT, `Body` INT, `Content` INT);

-- -----------------------------------------------------
-- View `gordcms`.`post_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gordcms`.`post_details`;
USE `gordcms`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `gordcms`.`post_details` AS select `gordcms`.`posts`.`Id` AS `ID`,`gordcms`.`posts`.`Title` AS `Title`,`gordcms`.`posts`.`Submit` AS `Submit`,`gordcms`.`categories`.`Id` AS `CategoryID`,`gordcms`.`categories`.`Name` AS `CategoryName`,`gordcms`.`users`.`id` AS `UserID`,`gordcms`.`users`.`username` AS `Username`,`gordcms`.`posts`.`Body` AS `Body`,`gordcms`.`posts`.`Content` AS `Content` from ((`gordcms`.`posts` join `gordcms`.`users` on((`gordcms`.`posts`.`UserId` = `gordcms`.`users`.`id`))) join `gordcms`.`categories` on((`gordcms`.`posts`.`CategoryId` = `gordcms`.`categories`.`Id`)));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
